"set autoindent

" Turn on line numbering. Turn it off with "set nonu" 
set number

" Set syntax on
syntax enable

"
filetype plugin indent on

" Case insensitive search
set noic

" Higlhight search
set hls

" Wrap text instead of being on one line
set lbr

syntax enable

set tabstop=2
set shiftwidth=2
set expandtab

execute pathogen#infect()

"set runtimepath^=~/.vim/bundle/vim-erlang-runtime/

set background=light
colorscheme solarized

set dictionary-=/usr/share/dict/words
set dictionary+=/usr/share/dict/words

au BufNewFile *.erl 0r ~/.vim/skel/erlang.skel 

"http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
let &t_SI.= "\e[6 q"
let &t_SR.= "\e[4 q"
let &t_EI.= "\e[2 q"

"https://unix.stackexchange.com/questions/433273/changing-cursor-style-based-on-mode-in-both-zsh-and-vim
autocmd VimEnter * silent exec "! echo -ne '\e[2 q'"
autocmd VimLeave * silent exec "! echo -ne '\e[6 q'"
